### ISSUE TITLE
errors on Win11

### ISSUE THREAD

**Issue by Lwy-1998** [ingra14m/Deformable-3D-Gaussians#23]
I tried to train Nerf-DS dataset on my Win11 platform
but i got this issue

> (gaussian_splatting) PS D:\3dgaussians\Deformable-3D-Gaussians> python train_gui.py -s .\data\NeRF-DS\as\ -m output/test1 --eval --is_blender
> Optimizing output/test1
> Output folder: output/test1 [06/12 08:56:40]
> Tensorboard not available: not logging progress [06/12 08:56:40]
> Found dataset.json file, assuming Nerfies data set! [06/12 08:56:40]
> Reading Nerfies Info [06/12 08:56:40]
>  [06/12 08:56:44]
> Loading Training Cameras [06/12 08:56:44]
> Loading Test Cameras [06/12 08:56:49]
> Number of points at initialisation :  20256 [06/12 08:56:52]
> Training progress:   0%|                                                                     | 0/40000 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "train_gui.py", line 773, in <module>
>     gui = GUI(args=args, dataset=lp.extract(args), opt=op.extract(args), pipe=pp.extract(args),testing_iterations=args.test_iterations, saving_iterations=args.save_iterations)
>   File "train_gui.py", line 134, in __init__
>     self.test_step()
>   File "C:\Users\Lwyy\miniconda3\envs\gaussian_splatting\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "train_gui.py", line 674, in test_step
>     out = render(viewpoint_camera=cur_cam, pc=self.gaussians, pipe=self.pipe, bg_color=self.background, d_xyz=d_xyz, d_rotation=d_rotation, d_scaling=d_scaling, is_6dof=self.dataset.is_6dof)
>   File "D:\3dgaussians\Deformable-3D-Gaussians\gaussian_renderer\__init__.py", line 63, in render
>     debug=pipe.debug,
> TypeError: __new__() got an unexpected keyword argument 'debug'

**Comment by Lwy-1998** [comment]
I successfully run on ubuntu. so never mind
