### ISSUE TITLE
About Issues of interpolate-view-task in Render.py

### ISSUE THREAD

**Issue by SkevyHoo** [ingra14m/Deformable-3D-Gaussians#51]
I run Render.py with --mode view commond, the result shows all rendered image is full black without the object. I wanna know what happened and how to resolve it.

**Comment by ingra14m** [comment]
Hi, thanks for your interest.

I carefully check the `render.py`, I'm sorry to say that I made a mistake in README. `view` mode is used for view-interpolation task for **synthetic scenes**.

In real-world scenes, due to the inaccurate camera pose and the unknown scene scale, we use the `interpolate_view_original` function (-mode original) that aligns the camera trajectory with the shooting camera.

**Comment by SkevyHoo** [comment]
Sorry, we used -mode view to render images of D-NeRF, and obtained the wrong result.

**Comment by ingra14m** [comment]
Sry again for my mistake.

I found that the function `interpolate_view` contains `render_wander_path`, which is used to render llff dataset in the early experiments. But the function is a dirty function, and can not run properly as its initial purpose.

You can refer to the following code for view synthesis task.
```python
def interpolate_view(model_path, load2gpt_on_the_fly, is_6dof, name, iteration, views, gaussians, pipeline, background, timer):
    render_path = os.path.join(model_path, name, "interpolate_view_{}".format(iteration), "renders")
    depth_path = os.path.join(model_path, name, "interpolate_view_{}".format(iteration), "depth")
    # acc_path = os.path.join(model_path, name, "interpolate_view_{}".format(iteration), "acc")

    makedirs(render_path, exist_ok=True)
    makedirs(depth_path, exist_ok=True)
    # makedirs(acc_path, exist_ok=True)

    frame = 150
    to8b = lambda x: (255 * np.clip(x, 0, 1)).astype(np.uint8)

    idx = torch.randint(0, len(views), (1,)).item()
    time_idx = views[idx].fid  # Choose a specific time for rendering

    # render_poses = torch.stack([pose_spherical(angle, -30.0, 4.0) for angle in np.linspace(-180, 180, frame + 1)[:-1]],
    #                            0)

    renderings = []
    for i, view in enumerate(tqdm(views, desc="Rendering progress")):
        xyz = gaussians.get_xyz
        time_input = fid.unsqueeze(0).expand(xyz.shape[0], -1)
        d_xyz, d_rotation, d_scaling = timer.step(xyz.detach(), time_input)
        results = render(view, gaussians, pipeline, background, d_xyz, d_rotation, d_scaling, is_6dof)
        rendering = results["render"]
        renderings.append(to8b(rendering.cpu().numpy()))
        depth = results["depth"]
        depth = depth / (depth.max() + 1e-5)

        torchvision.utils.save_image(rendering, os.path.join(render_path, '{0:05d}'.format(i) + ".png"))
        torchvision.utils.save_image(depth, os.path.join(depth_path, '{0:05d}'.format(i) + ".png"))
        # torchvision.utils.save_image(acc, os.path.join(acc_path, '{0:05d}'.format(i) + ".png"))

    renderings = np.stack(renderings, 0).transpose(0, 2, 3, 1)
    imageio.mimwrite(os.path.join(render_path, 'video.mp4'), renderings, fps=30, quality=8)
```

**Comment by grisaiakaziki** [comment]
Thank you for your awesome work!
When I perform rendering, I encounter a problem. How should I solve it?
The dataset I am using is cookie. The environment is python=3.8 ,torch=2.2.2. 
My training command is , 
python train.py -s path/to/your/real-world/dataset -m output/exp-name --eval --is_6dof --iterations 20000

and the rendering command is this.

python render.py -m output/cookie --mode original

 When I select the mode as "original," this problem occurs.

Looking for config file in output/cookie/cfg_args
Config file found: output/cookie/cfg_args
Rendering output/cookie
Loading trained model at iteration 20000 [20/06 20:55:59]
Found dataset.json file, assuming Nerfies data set! [20/06 20:55:59]
Reading Nerfies Info [20/06 20:55:59]
 [20/06 20:56:01]
Loading Training Cameras [20/06 20:56:01]
Loading Test Cameras [20/06 20:56:01]
Rendering progress:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 993/1000 [01:32<00:00, 10.77it/s]
IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (536, 960) to (544, 960) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
[swscaler @ 0x72ac040] Warning: data is not aligned! This can lead to a speed loss
Traceback (most recent call last):
  File "render.py", line 386, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode)
  File "render.py", line 365, in render_sets
    render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter,
  File "render.py", line 297, in interpolate_view_original
    view = views[0]
IndexError: list index out of range

and when the mode is  render 

Looking for config file in output/cookie/cfg_args
Config file found: output/cookie/cfg_args
Rendering output/cookie
Loading trained model at iteration 20000 [20/06 20:55:23]
Found dataset.json file, assuming Nerfies data set! [20/06 20:55:23]
Reading Nerfies Info [20/06 20:55:23]
 [20/06 20:55:25]
Loading Training Cameras [20/06 20:55:25]
Loading Test Cameras [20/06 20:55:25]
Rendering progress: 0it [00:00, ?it/s]
Rendering progress: 0it [00:00, ?it/s]
render.py:73: RuntimeWarning: Mean of empty slice.
  fps = 1.0 / t.mean()
/home/summer/miniconda3/envs/deformable_gs/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "render.py", line 386, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode)
  File "render.py", line 365, in render_sets
    render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter,
  File "render.py", line 74, in render_set
    print(f'Test FPS: \033[1;35m{fps:.5f}\033[0m, Num. of GS: {xyz.shape[0]}')
UnboundLocalError: local variable 'xyz' referenced before assignment

**Comment by grisaiakaziki** [comment]
I found that the “scene” could not load the camera of the test set.

**Comment by xdh096** [comment]
> Thank you for your awesome work! When I perform rendering, I encounter a problem. How should I solve it? The dataset I am using is cookie. The environment is python=3.8 ,torch=2.2.2. My training command is , python train.py -s path/to/your/real-world/dataset -m output/exp-name --eval --is_6dof --iterations 20000
> 
> and the rendering command is this.
> 
> python render.py -m output/cookie --mode original
> 
> When I select the mode as "original," this problem occurs.
> 
> Looking for config file in output/cookie/cfg_args Config file found: output/cookie/cfg_args Rendering output/cookie Loading trained model at iteration 20000 [20/06 20:55:59] Found dataset.json file, assuming Nerfies data set! [20/06 20:55:59] Reading Nerfies Info [20/06 20:55:59] [20/06 20:56:01] Loading Training Cameras [20/06 20:56:01] Loading Test Cameras [20/06 20:56:01] Rendering progress: 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 993/1000 [01:32<00:00, 10.77it/s] IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (536, 960) to (544, 960) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility). [swscaler @ 0x72ac040] Warning: data is not aligned! This can lead to a speed loss Traceback (most recent call last): File "render.py", line 386, in render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode) File "render.py", line 365, in render_sets render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter, File "render.py", line 297, in interpolate_view_original view = views[0] IndexError: list index out of range
> 
> and when the mode is render
> 
> Looking for config file in output/cookie/cfg_args Config file found: output/cookie/cfg_args Rendering output/cookie Loading trained model at iteration 20000 [20/06 20:55:23] Found dataset.json file, assuming Nerfies data set! [20/06 20:55:23] Reading Nerfies Info [20/06 20:55:23] [20/06 20:55:25] Loading Training Cameras [20/06 20:55:25] Loading Test Cameras [20/06 20:55:25] Rendering progress: 0it [00:00, ?it/s] Rendering progress: 0it [00:00, ?it/s] render.py:73: RuntimeWarning: Mean of empty slice. fps = 1.0 / t.mean() /home/summer/miniconda3/envs/deformable_gs/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount) Traceback (most recent call last): File "render.py", line 386, in render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode) File "render.py", line 365, in render_sets render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter, File "render.py", line 74, in render_set print(f'Test FPS: \033[1;35m{fps:.5f}\033[0m, Num. of GS: {xyz.shape[0]}') UnboundLocalError: local variable 'xyz' referenced before assignment

I also encountered the same problem in HyperNeRF data set, did you solve it?

**Comment by chenj02** [comment]
> > Thank you for your awesome work! When I perform rendering, I encounter a problem. How should I solve it? The dataset I am using is cookie. The environment is python=3.8 ,torch=2.2.2. My training command is , python train.py -s path/to/your/real-world/dataset -m output/exp-name --eval --is_6dof --iterations 20000
> > and the rendering command is this.
> > python render.py -m output/cookie --mode original
> > When I select the mode as "original," this problem occurs.
> > Looking for config file in output/cookie/cfg_args Config file found: output/cookie/cfg_args Rendering output/cookie Loading trained model at iteration 20000 [20/06 20:55:59] Found dataset.json file, assuming Nerfies data set! [20/06 20:55:59] Reading Nerfies Info [20/06 20:55:59] [20/06 20:56:01] Loading Training Cameras [20/06 20:56:01] Loading Test Cameras [20/06 20:56:01] Rendering progress: 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 993/1000 [01:32<00:00, 10.77it/s] IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (536, 960) to (544, 960) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility). [swscaler @ 0x72ac040] Warning: data is not aligned! This can lead to a speed loss Traceback (most recent call last): File "render.py", line 386, in render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode) File "render.py", line 365, in render_sets render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter, File "render.py", line 297, in interpolate_view_original view = views[0] IndexError: list index out of range
> > and when the mode is render
> > Looking for config file in output/cookie/cfg_args Config file found: output/cookie/cfg_args Rendering output/cookie Loading trained model at iteration 20000 [20/06 20:55:23] Found dataset.json file, assuming Nerfies data set! [20/06 20:55:23] Reading Nerfies Info [20/06 20:55:23] [20/06 20:55:25] Loading Training Cameras [20/06 20:55:25] Loading Test Cameras [20/06 20:55:25] Rendering progress: 0it [00:00, ?it/s] Rendering progress: 0it [00:00, ?it/s] render.py:73: RuntimeWarning: Mean of empty slice. fps = 1.0 / t.mean() /home/summer/miniconda3/envs/deformable_gs/lib/python3.8/site-packages/numpy/core/_methods.py:192: RuntimeWarning: invalid value encountered in scalar divide ret = ret.dtype.type(ret / rcount) Traceback (most recent call last): File "render.py", line 386, in render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.mode) File "render.py", line 365, in render_sets render_func(dataset.model_path, dataset.load2gpu_on_the_fly, dataset.is_6dof, "test", scene.loaded_iter, File "render.py", line 74, in render_set print(f'Test FPS: \033[1;35m{fps:.5f}\033[0m, Num. of GS: {xyz.shape[0]}') UnboundLocalError: local variable 'xyz' referenced before assignment
> 
> I also encountered the same problem in HyperNeRF data set, did you solve it?

Me too, I also encountered the same problem in HyperNeRF data set, did you solve it?

**Comment by respect-jz** [comment]
> Me too, I also encountered the same problem in HyperNeRF data set, did you solve it?

@chenj02

**Comment by respect-jz** [comment]
did you solve it?
@chenj02

**Comment by MiaoQiaowei** [comment]
Perhaps the PSNR  is calculated between the training ground truth and the rendered images from the training viewpoints？
