### ISSUE TITLE
When following the tutorial, I encountered the following problem, how to deal with this parameter

### ISSUE THREAD

**Issue by ZZZZZHHHHHSSSSS** [ingra14m/Deformable-3D-Gaussians#59]
(deformable_gaussian_env) E:\DeepLearning\Deformable-3D-Gaussians-main>python train.py -s E:\DeepLearning\Deformable-3D-Gaussians-main\data\D-NeRF\hook -m output/exp-name --eval --is_blender
Optimizing output/exp-name
Output folder: output/exp-name [29/05 13:04:22]
Tensorboard not available: not logging progress [29/05 13:04:22]
Found transforms_train.json file, assuming Blender data set! [29/05 13:04:22]
Reading Training Transforms [29/05 13:04:22]
Reading Test Transforms [29/05 13:04:26]
Loading Training Cameras [29/05 13:04:27]
Loading Test Cameras [29/05 13:04:30]
Number of points at initialisation :  100000 [29/05 13:04:30]
Training progress:   0%|                                                                     | 0/40000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 275, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "train.py", line 100, in training
    render_pkg_re = render(viewpoint_cam, gaussians, pipe, background, d_xyz, d_rotation, d_scaling, dataset.is_6dof)
  File "E:\DeepLearning\Deformable-3D-Gaussians-main\gaussian_renderer\__init__.py", line 117, in render
    cov3D_precomp=cov3D_precomp)
  File "E:\Anaconda3\envs\deformable_gaussian_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'means2D_densify'

**Comment by ingra14m** [comment]
Hi, you may need to update the latest diff-gaussian-rasterization.

You can reclone the repo the get the latest rasterization. `git clone https://github.com/ingra14m/Deformable-3D-Gaussians --recursive`

**Comment by ZZZZZHHHHHSSSSS** [comment]
> Hi, you may need to update the latest diff-gaussian-rasterization.
> 
> You can reclone the repo the get the latest rasterization. `git clone https://github.com/ingra14m/Deformable-3D-Gaussians --recursive`

Thank U very much！I'm still a vegitable bird（Chinglish） in the use of github. Thanks for being willing to answer such a basic question.

**Comment by DingChunQ** [comment]
> Hi, you may need to update the latest diff-gaussian-rasterization.
> 
> You can reclone the repo and get the latest rasterization. `git clone https://github.com/ingra14m/Deformable-3D-Gaussians --recursive`

Sorry, I did this, but Error still occurs.

**Comment by phb-shiyige-fw** [comment]
> Hi, you may need to update the latest diff-gaussian-rasterization.
> 
> You can reclone the repo and get the latest rasterization. `git clone https://github.com/ingra14m/Deformable-3D-Gaussians --recursive`

Thanks for getting the point about this question. But something limited made me cant used Git（because of company's limited net), how can I get the latest rasterization?

**Comment by phb-shiyige-fw** [comment]
> Hi, you may need to update the latest diff-gaussian-rasterization.
> 
> You can reclone the repo and get the latest rasterization. `git clone https://github.com/ingra14m/Deformable-3D-Gaussians --recursive`

I tried to update the rasterization, but still got this problem, how to solve this?

**Comment by ingra14m** [comment]
Then you need to pip install submodules/depth-diff-gaussian-rasterization

**Comment by doublepoints** [comment]
I have also met this problem.
By the way, I am using the paper-version.
Can you give me some suggestion?

**Comment by 1713949** [comment]
I downloaded the diff-gaussian-rasterization from the link, but there is still a problem with the means2D_densify parameter. I also tried the original 3dgs diff-gaussian-rasterization, but it still doesn't work.
(deformable) ubuntu@ubuntu-ywq:~/data01/dhm/Deformable-3D-Gaussians$ pip install -e submodules/diff-gaussian-rasterization
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/ubuntu/data01/dhm/Deformable-3D-Gaussians/submodules/diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Installing collected packages: diff-gaussian-rasterization
  DEPRECATION: Legacy editable install of diff-gaussian-rasterization==0.0.0 from file:///home/ubuntu/data01/dhm/Deformable-3D-Gaussians/submodules/diff-gaussian-rasterization (setup.py develop) is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for diff-gaussian-rasterization
Successfully installed diff-gaussian-rasterization
(deformable) ubuntu@ubuntu-ywq:~/data01/dhm/Deformable-3D-Gaussians$ python3 train.py -s /home/ubuntu/data01/dhm/Deformable-3D-Gaussians/data/hook/ -m /home/ubuntu/data01/dhm/Deformable-3D-Gaussians/output/hook/ --eval --is_blender
Optimizing /home/ubuntu/data01/dhm/Deformable-3D-Gaussians/output/hook/
Output folder: /home/ubuntu/data01/dhm/Deformable-3D-Gaussians/output/hook/ [15/04 12:11:54]
Found transforms_train.json file, assuming Blender data set! [15/04 12:11:55]
Reading Training Transforms [15/04 12:11:55]
Reading Test Transforms [15/04 12:12:00]
Generating random point cloud (100000)... [15/04 12:12:01]
Loading Training Cameras [15/04 12:12:01]
Loading Test Cameras [15/04 12:12:04]
Number of points at initialisation :  100000 [15/04 12:12:04]
Training progress:   0%|                                                                    | 0/40000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/data01/dhm/Deformable-3D-Gaussians/train.py", line 275, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations)
  File "/home/ubuntu/data01/dhm/Deformable-3D-Gaussians/train.py", line 100, in training
    render_pkg_re = render(viewpoint_cam, gaussians, pipe, background, d_xyz, d_rotation, d_scaling, dataset.is_6dof)
  File "/home/ubuntu/data01/dhm/Deformable-3D-Gaussians/gaussian_renderer/__init__.py", line 108, in render
    rendered_image, radii, depth = rasterizer(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: GaussianRasterizer.forward() got an unexpected keyword argument 'means2D_densify'
Training progress:   0%|                                                                    | 0/40000 [00:00<?, ?it/s]
(deformable) ubuntu@ubuntu-ywq:~/data01/dhm/Deformable-3D-Gaussians$

![Image](https://github.com/user-attachments/assets/194f9852-a50f-4dcb-8af8-ec712b5db412)
